name: PR to Develop Analysis

on:
  pull_request:
    branches: [develop]

jobs:
  call-sonar:
    uses: microservices-final-project/ci-templates/.github/workflows/sonarqube-analysis.yaml@main
    with:
      projectKey: favourite-service
      projectName: Favourite Service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
